---
site_name: mottosso
site_description: Open Source software for VFX
site_author: mottosso
site_url: https://mottosso.com

copyright: "Copyright &copy; 2019 mottosso"

# Page tree
nav:
  - Home: index.md

docs_dir: pages
edit_uri: edit/master/docs/pages/

theme:
  name: material
  logo: logo.png
  custom_dir: theme
  palette:
    primary: "white"
    accent: "white"

extra_css:
  - extra.css

# Options
extra:
  feature:
    tabs: true

extra_javascript:
  - "extra.js"

markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
      # linenums: true
      pygments_style: monokai
  - markdown.extensions.extra
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - search
